title: lincoln go club
email: play@lincolngo.club
description: >- # this means to ignore newlines until "baseurl:"
  home of lincoln go club
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lincolngo.club" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
permalink:      /:year/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
